### ISSUE TITLE
a few comments on chapter3/aishah/challenge.[R|py]

### ISSUE THREAD

**Issue by paul-shannon** [PriceLab/STP#4]
@aishahmohamed98 
Good work, Aishah.

Just a few small comments and questions:

1.  the R version, first exercise, says ````print(paste(i))````.  What does the paste do?
2. Though not mandatory, in R the use of ````<-```` for all assignments is encouraged, rather than ````=````.   You should only use ````=```` in the assignment of elements of a named list.
3.  The variable ````i```` is traditionally used for integer indices in a for loop.  Good practice is to use clear & self-documenting names:
````
isb.employees <- c("aishah", "omar", "paul")\
for(employee in employees)
    print(employee)
````
4. Your use of ````//```` is illegal!   What is the right comment character for R?  For python? For javascript?

Please fix these things, answer these questions, move on to the next.  Keep up the good work!
- Palu

**Comment by aishahmohamed98** [comment]
1. upon some research, paste seemed appropriate because it converted arguments into strings but i can see how its redundant as our names are already character strings. 
4. commenting in python is using #, javascript uses // and /*  ending with */ , and commenting in r is with a #.

i've uploaded the updated version please feel free to review and comment on it if you'd like.

**Comment by paul-shannon** [comment]
Well done - exactly right.
In addition to executing the code, line by line (or chunk by chunk) from within ESS and elpy, I also did this, without errors:
````
   bash> R -f challenges.R
   bash> python challenge.py
````
Try this in your bash shell, just for good measure.
Functions and "containers" (aka "data structures") next!
